name: Python application

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v1
      - v1.*

jobs:
  build:
    name: actions-ci
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ['3.5','3.6','3.7']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -V
        pwd && ls -lRt && uname -r
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip -V && pip list
    - name: Docker setup
      run: |
        docker version
        docker-compose version
    - name: Exec Pytest
      run: |
        pytest --version
        pytest -vv
        pytest -vv --cov=.
