name: Python application

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v1
      - v1.*

jobs:
  build:
    name: actions-ci
    # runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04']
        python: ['3.6','3.7']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ./script/info.sh
    - name: Docker setup
      run: |
        docker version
        docker-compose version
    - name: Exec Pytest
      run: |
        pytest --version
        pytest -vv
        pytest -vv --cov=.
